### Login
POST http://127.0.0.1:8000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "daniel@email",
    "password": "daniel54321"
}

### Perfil
GET http://127.0.0.1:8000/api/auth/profile
Accept: application/json
Authorization: Bearer 7|bMLc26BLbzLEUMkJOVG5CvmSp4tFnhKaIaBYI3yh282d48f1

### Salir
POST http://127.0.0.1:8000/api/auth/logout
Accept: application/json
Authorization: Bearer 7|bMLc26BLbzLEUMkJOVG5CvmSp4tFnhKaIaBYI3yh282d48f1

